# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  providers:
    api_key_user_provider:
        id: api_key_user_provider
  firewalls:
    login:
        pattern:  ^/login$
        anonymous: true
    forgot_password:
        pattern:  ^/forgot_password$
        anonymous: true
    reset_password:
        pattern:  ^/reset_password$
        anonymous: true
    secured_area:
        pattern: ^/
        stateless: true
        simple_preauth:
            authenticator: apikey_authenticator
        provider: api_key_user_provider
        anonymous: false
  access_control:
    - { path: ^/, roles: ROLE_API }
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/forgot_password$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reset_password$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
