# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  providers:
    api_key_user_provider:
        id: api_key_user_provider
  firewalls:
    login:
        pattern:  ^/login$
        security: false
    forgot_password:
        pattern:  ^/forgot_password$
        security: false
    reset_password:
        pattern:  ^/reset_password$
        security: false
    secured_area:
        pattern: ^/
        stateless: true
        simple_preauth:
            authenticator: apikey_authenticator
        provider: api_key_user_provider
  access_control:
    - { path: ^/, roles: ROLE_API }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/forgot_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reset_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
