login:
    path:      /login
    defaults:  { _controller: AppBundle:User:login }
    methods:  POST
logout:
    path:      /logout
    defaults:  { _controller: AppBundle:User:logout }
    methods:  POST
forgot_password:
    path:      /forgot_password
    defaults:  { _controller: AppBundle:User:forgotPassword }
    methods:  POST
reset_password:
    path:      /reset_password
    defaults:  { _controller: AppBundle:User:resetPassword }
    methods:  POST
get_user:
    path:      /user/get
    defaults:  { _controller: AppBundle:User:getUser }

update_user:
    path:      /user/update
    defaults:  { _controller: AppBundle:User:updateUser }
    methods:  POST
    
get_list_user:
    path:      /user/list
    defaults:  { _controller: AppBundle:User:getList }

get_sensor:
    path:      /sensor/get
    defaults:  { _controller: AppBundle:Sensor:getSensor }

get_list_sensor:
    path:      /sensor/list
    defaults:  { _controller: AppBundle:Sensor:getList }

get_virtual_sensor:
    path:      /virtual-sensor/get
    defaults:  { _controller: AppBundle:VirtualSensor:getVirtualSensor }

get_list_virtual_sensor:
    path:      /virtual-sensor/list
    defaults:  { _controller: AppBundle:VirtualSensor:getList }

get_farm:
    path:      /farm/get
    defaults:  { _controller: AppBundle:Farm:getFarm }

get_list_farm:
    path:      /farm/list
    defaults:  { _controller: AppBundle:Farm:getList }

get_rules:
    path:      /rules/get
    defaults:  { _controller: AppBundle:Rules:get }

update_rules:
    path:      /rules/update
    defaults:  { _controller: AppBundle:Rules:update }
    methods:  POST
delete_rules:
    path:      /rules/delete
    defaults:  { _controller: AppBundle:Rules:delete }
    methods:  POST
add_rules:
    path:      /rules/add
    defaults:  { _controller: AppBundle:Rules:add }
    methods:  POST
get_list_rules:
    path:      /rules/list
    defaults:  { _controller: AppBundle:Rules:getList }

get_report:
    path:      /report
    defaults:  { _controller: AppBundle:Report:get }

pust_notification:
    path:      /push
    defaults:  { _controller: AppBundle:Push:index }
    methods:  POST
