AppBundle\Entity\DatasCell2:
    type:  entity
    table: datascell2
    id:
        EUI:
            type: string
        dateLastUpdate:
            type: string
    fields:
        timeStamp:
            type: string
        temperature2:
            type: decimal
            precision: 4
            scale: 2
        humidity2:
            type: decimal
            precision: 4
            scale: 2