AppBundle\Entity\Datas:
    type:  entity
    table: datas
    id:
        EUI:
            type: string
        dateLastUpdate:
            type: string
    fields:
        timeStamp:
            type: string
        temperature1:
            type: decimal
            precision: 4
            scale: 2
        humidity1:
            type: decimal
            precision: 4
            scale: 2